#ifndef UI_DEFINITIONS_H
#define UI_DEFINITIONS_H

#define ACTIVE_UI_ELEM_COLOR_PAIR 1
#define INVALID_UI_ELEM_COLOR_PAIR 2
#define INACTIVE_UI_ELEM_COLOR_PAIR 3
#define INACTIVE_INVALID_UI_ELEM_COLOR_PAIR 4

#define NUM_RESERVED_COLORS 16
#define NUM_RESERVED_PAIRS 4

#endif
